### PR TITLE
add typescript template

### PR DESCRIPTION
**Pull request by druppy**
As requested in the forum, I have here made the changes against your template repos, as a PR.

### CODE REVIEW

**Comment by rstoenescu** [comment]
Thanks!!

Will do a test myself this week and then officially release this template.
You'll be fully credited as this is your work completely.

It currently works if you do `$ quasar init default#typescript <folder_name>`.

**Comment by druppy** [comment]
Perfect, it is just a small contribution and nothing compared too all your nice work.

I have a problem using webpack 2 as due to the missing proxy, but I will use the current stable version locally.

`tsx` files and a more detailed `index.d.ts` file will be the next goal, and as I start using this nice framework these thing will come sneaking :-)

**Comment by rstoenescu** [comment]
Let me know when you think this template is ready for a production release ;) I'll chime in to help too if I have time, but as things stand at the moment I don't think this is going to happen any time soon unfortunately.

**Comment by druppy** [comment]
Ok, just tried to init a fresh new project using your `quasar`tool, and it worked like a charm :-)

**Pull request merged**
